name: smartfarm
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  lottie: ^2.1.0
  # For Model
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  # For Architecture MVVM
  pmvvm: ^4.0.1
    # border dashed or dotted
  dotted_border: ^2.0.0+3
  flutter_dash: ^1.0.0
  # Path Provider
  path_provider: ^2.0.11
  # State Management, Route Management, Dependency Management
  get: ^4.6.5
  get_storage: ^2.0.3
  # Date Format
  intl: ^0.18.0
  # Firebase
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  firebase_auth: ^4.2.2
  firebase_messaging: ^14.2.1
  firebase_storage: ^11.0.10
  # For Image Caching
  cached_network_image: ^3.2.3
  # For Get App Info
  package_info_plus: ^3.0.2
  # to Generate Unique ID
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # For Model
  freezed: ^2.2.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
        - assets/images/
        - assets/icons/
        - assets/icons/svg/
        - assets/animations/
        - assets/fonts/

  fonts:
        - family: WorkSans
          fonts:
              - asset: assets/fonts/WorkSans-Regular.ttf
              - asset: assets/fonts/WorkSans-Medium.ttf
              - asset: assets/fonts/WorkSans-SemiBold.ttf
